config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  
  resources :users, only: [:create, :destroy, :new]
  resource :session, only: [:create, :destroy, :new]
  
  namespace :api, defaults: { format: :json } do
    resources :gigs, only: [:create, :destroy, :show, :index] do
      resources :reviews, only: [:index]
    end
    resources :gigextras, only: [:create, :update, :destroy]
    resources :users, only: [:show, :update] do
      resources :reviews, only: [:index]
    end
    resources :orders, only: [:create, :show]
    resources :likes, only: [:create]
    delete 'likes', to: 'likes#destroy'
  end
  
end

app/models/gig.rb
# == Schema Information
#
# Table name: gigs
#
#  id          :integer          not null, primary key
#  title       :string(255)      not null
#  creator_id  :integer          not null
#  price       :integer          not null
#  created_at  :datetime
#  updated_at  :datetime
#  image_url   :string(255)
#  description :text             not null
#

class Gig < ActiveRecord::Base
  validates :title, :creator, :price, :description, :image_url, presence: true
  
  belongs_to(
    :creator,
    class_name: "User",
    foreign_key: :creator_id,
    primary_key: :id
  )
  
  has_many(
    :extras,
    class_name: "GigExtra",
    foreign_key: :gig_id,
    primary_key: :id
  )

  has_many :likes
  has_many :orders
  
  has_many :reviews, through: :orders, source: :review
  
  def liked_by?(user)
    return false if user.nil?
    likes.any? { |like| like.user_id == user.id }
  end
     
end

app/models/gig_extra.rb
# == Schema Information
#
# Table name: gig_extras
#
#  id         :integer          not null, primary key
#  gig_id     :integer          not null
#  title      :string(255)      not null
#  price      :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class GigExtra < ActiveRecord::Base
  validates :title, :price, :gig, presence: true
  
  belongs_to :gig
  
  
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :integer          not null, primary key
#  gig_id     :integer          not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Like < ActiveRecord::Base
  validates :gig, :user, presence: true
  validates :gig_id, :uniqueness => { :scope => :user_id }
  
  belongs_to :gig
  belongs_to :user
  
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  buyer_id   :integer          not null
#  gig_id     :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  fulfilled  :boolean          default(FALSE), not null
#

class Order < ActiveRecord::Base
  validates :buyer, :gig, presence: true
  
  belongs_to :gig
    
  belongs_to(
    :buyer,
    class_name: "User",
    foreign_key: :buyer_id,
    primary_key: :id
  )
  
  has_many :order_extras
  
  has_one :review
  
  has_many :gig_extras, through: :order_extras, source: :gig_extra
  
  def total_price
    total_price = gig.price
    
    self.gig_extras.each do |gig_extra|
      total_price += gig_extra.price
    end
    
    total_price
  end
end

app/models/order_extra.rb
# == Schema Information
#
# Table name: order_extras
#
#  id           :integer          not null, primary key
#  order_id     :integer          not null
#  gig_extra_id :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class OrderExtra < ActiveRecord::Base
  belongs_to :order
  belongs_to :gig_extra
end

app/models/order_extras.rb
# == Schema Information
#
# Table name: order_extras
#
#  id           :integer          not null, primary key
#  order_id     :integer          not null
#  gig_extra_id :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class OrderExtras < ActiveRecord::Base
  
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id         :integer          not null, primary key
#  content    :string(255)      not null
#  stars      :integer          not null
#  order_id   :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Review < ActiveRecord::Base
  validates :content, :order, :buyer, :gig, presence: true
  validates :stars, inclusion: { in: 1..5 }
  validates :order_id, :uniqueness => true
  belongs_to :order
  
  delegate :buyer, to: :order#, allow_nil: true
  delegate :gig, to: :order

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#  creator_desc    :string(255)
#  image_url       :string(255)      default("/assets/default-avatar.jpg"), not null
#  email           :string(255)      default("default@gmail.com"), not null
#

class User < ActiveRecord::Base
  validates :username, :session_token, :email, presence: true
  validates :password, length: { minimum: 4, allow_nil: true }
  validates :username, uniqueness: true
  
  after_initialize :ensure_session_token
  
  has_many(
    :gigs,
    class_name: "Gig",
    foreign_key: :creator_id,
    primary_key: :id
  )
  
  has_many(
    :orders,
    class_name: "Order",
    foreign_key: :buyer_id,
    primary_key: :id
  )
  
  has_many :reviews, through: :orders, source: :review
  
  has_many :reviews_on_self, through: :gigs, source: :reviews
  
  has_many :likes
  
  def password
    @password
  end 
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def generate_token
    SecureRandom.base64(16)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return user if user && user.is_password?(password) 
    nil
  end
  
  def reset_session_token!
    self.session_token = generate_token
    self.save
    self.session_token
  end
  
  def other_gigs(gig_id)
    self.gigs.reject { |gig| gig.id == gig_id }
  end
  
  private
  
  def ensure_session_token
    self.session_token ||= generate_token
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :login!, :current_user, :logged_in?
  
  def login!(user)
    return nil if user.nil?
    session[:session_token] = user.reset_session_token!
  end
  
  def logout!(user)
    session[:session_token] = nil
    user.reset_session_token!
  end
  
  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  
  def self.current_user
    current_user
  end
  def logged_in?
    !!current_user
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password] 
    )
    if user #this method uses params
      login!(user)
      redirect_to root_url
    else
      flash[:errors] = ["Invalid Username and/or Password. Try again"]
      redirect_to new_session_url
    end
    
  end
  
  def destroy
    logout!(current_user)
    redirect_to root_url
  end
  
  private
  
  def session_params
    params.require(:user).permit(:username, :password)
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def root
    render :root
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def create
    user = User.new(user_params)
    if user.save
      login!(user)
      redirect_to root_url
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_url
    end
  end
  
  def destroy
    user = current_user
    user.destroy
    redirect_to new_user_url
  end
  
  def new
    render :new
  end

  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/api/likes_helper.rb
module Api::LikesHelper
end

app/helpers/api/orders_helper.rb
module Api::OrdersHelper
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/sessions_controller_helper.rb
module SessionsControllerHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% flash[:errors].each do |error| %>
  <div class="bg-warning error alert alert-warning" role="alert"><%= error %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer-main">
    <ul class="links-index">
      <li><a href="#" onclick="return false;">About Us</a></li>
      <li><a href="http://www.linkedin.com/pub/aaron-cordovez/96/108/765/">About Our Founder</a></li>
      <li><a href="#" onclick="return false;">Careers</a></li>
      <li><a href="#" onclick="return false;">Privacy</a></li>
      <li><a href="#" onclick="return false;">Sellers</a></li>
    </ul>
    
    <div class="copyright-notice">&#169; OmniFive International LLC </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="loginModalLabel">Log in</h4>
      </div>
      
      <div class="modal-body">
        <form action="<%= session_url %>" method="POST" role="form"> 
          <input type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

          <div class="form-group">
            <label for="username">Username: </label>
            <input type="text"
              name="user[username]"
              id="username"
              class="form-control">
          </div>
        
          <div class="form-group">
            <label for="password">Password: </label>
            <input type="password"
              name="user[password]"
              class="form-control"
              id="password">
          </div>
          
          <input type="submit" class="btn btn-primary" value="Log in">
        </form>
      </div>
    </div>
  </div>
</div>

<!-- End Login Modal -->


<!-- Signup Modal -->

<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="signupLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="signUpModalLabel">Sign up</h4>
      </div>
      
      <div class="modal-body">
        
        <form action="<%= users_url %>" method="POST" role="form"> 

          <input type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
          
          <div class="form-group">
            <label for="username">Username: </label>
            <input type="text"
              name="user[username]"
              id="username"
              class="form-control">
          </div>
          
          <div class="form-group">
            <label for="password">Password: </label>
            <input type="password"
              name="user[password]"
              id="password"
              class="form-control">
          </div>
          <input type="submit" class="btn btn-primary" value="Sign Up">
        </form>

    
      </div>
    </div>
  </div>
</div>

<!-- End Signup Modal -->

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= logged_in? ? "#" : "/" %>"><span class="theme-blue">Omni</span>Five <sup>&#169;</sup></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li id="home-tab"><a href="<%= logged_in? ? "#" : "/" %>">Home <span class="sr-only">(current)</span></a></li>

        </li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" id="current-user-tab" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Currently logged in as <%= current_user.username %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li id="new-gig-tab"><a href="#gigs/new">Make a new Gig</a></li>
              <li class="divider"></li>
              <li><a href="#users/<%= current_user.id %>">My profile</a></li>
              <li id="edit-user-tab"><a href="#users/<%= current_user.id %>/edit">Edit profile</a></li>
            </ul>

        <li><%= button_to "Log out", session_url, method: "delete", class: "btn btn-default navbar-btn" %></li>
          <!-- <%= button_to "Delete Account", user_url(current_user.id), method: "delete" %> -->
        <% else %>
        <li data-toggle="modal" 
          data-target="#signupModal"><a href="#">Sign up</a></li>
        
        <li data-toggle="modal" 
          data-target="#loginModal"><a href="#">Log in</a></li>

        <% end %>
        

        
        
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
        
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if flash[:errors] %>
  <%= render 'layouts/errors' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OmniFive</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= filepicker_js_include_tag %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <script>
    filepicker.setKey("<%= ENV['FILEPICKER_API_KEY'] %>");
  </script>
  <link href="//fonts.googleapis.com/css?family=Oxygen:300,400,700" rel="stylesheet" type="text/css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

</head>
<body>
  <div class="page-wrap">
    
    <%= render 'layouts/header' %>  
    <%= yield %>
    
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>